title : mape strumenti
baseurl: "http://mape-strumenti.it"
description: "Guitars and basses for passion. Based in Rome, Italy"
feed-description: "RSS Feeds for the website"
copyright: "2022"
markdown: kramdown

greeting: "Welcome"
headline: "Guitars and basses for passion. Based in Rome, Italy"
logo: assets/images/logo.svg

image: /assets/img/og-image.png

author :
  name : Mape Strumenti
  headline: "Guitars and basses for passion. Based in Rome, Italy"
  image: assets/img/mape-logoWeb-768x184.png
  avatar: 
    src : assets/img/avatar.jpg
    srcset : 
      - assets/img/avatar-1x.jpg
      - assets/img/avatar-2x.jpg
      - assets/img/avatar-3x.jpg
      - assets/img/avatar-4x.jpg

contact:
    email:  info@mape-strumenti.it
    instagram: mape_strumenti
      
include: ["_instruments"]
# Sass settings
sass:
  sass_dir: assets/css
  style: compressed

# Set collections
collections:
  instruments:
    output: true
  categories:
    output: true
plugins:
  - jekyll-sitemap

lang: en


# Manifest settings (Used to make manifest.json)
# Edit manifest.json directly with icon information
manifest_name: mape-strumenti.it
manifest_short_name: "mape-strumenti.it" # Appears in "Add to home screen" dialogues
manifest_lang: en
manifest_background_color: white
manifest_display: standalone